create table public.licenses (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  hardware_id character varying null,
  access_granted character varying null default 'LIMITED'::character varying,
  supporter_name character varying null,
  supporter_email character varying null,
  telegram_chat_id bigint null,
  constraint licenses_pkey primary key (id),
  constraint licenses_hardware_id_key unique (hardware_id)
) TABLESPACE pg_default;

